### ISSUE TITLE
Complete repo checklist 

### ISSUE THREAD

**Issue by sahra-karakoc** [graphops/graph-network-substreams#5]
This includes:
- [x]  `README.md`
    Sections:
   - [x]  Introduction
   - [x]  Features
   - [x]  Quickstart
   - [ ]  Configuring
   - [ ]  Upgrading
   - [x]  Contributing
- [x]  `CONTRIBUTORS.md`
- [x]  `SECURITY.md`
- [x]  Pull Request Template
- [x]  `CODE_OF_CONDUCT.md`
- [x]  License (Apache 2)
- [x]  CD 
- [ ]  Has automated release/changelog generation ?
- [x]  Has commit hooks that enforce (via husky)
    - [x]  conventional commits
    - [ ]  changelog generation
- [ ]  Add [https://github.com/graphops/admin/blob/main/.github/suborgs/public.yml](https://github.com/graphops/admin/blob/main/.github/suborgs/public.yml) if public
- [x]  Add description and tags defined here: [https://github.com/graphops/admin/tree/main/.github/repos](https://github.com/graphops/admin/tree/main/.github/repos)
- [x] Decent documentation for users
